### Criar um Novo Grupo de Consórcio
POST http://localhost:8080/grupos/criar
Content-Type: application/json

{
  "nome": "Consorcio jaraguá 2026",
  "valorCota": 1050.00,
  "vagasMaximas": 100,
  "duracaoMeses": 90,
  "enderecoContrato": "0x9999bB67C8901234567890abcdef1234567890cc",
  "aceitaLances": true,
  "tipoLanceAdicional": "LIVRE"
}
### Criar um novo usuário
POST http://localhost:8080/usuarios
Content-Type: application/json

{
"nome": "Alice Silva",
"email": "alice@email.com",
  "senhaLimpa": "132fdas9fh",
"taxId": "123.456.789-00",
"carteiraWeb3": "0x9999bB67C8901234567890abcdef1234567890aa",
  "countryCode": "BR"
}

###cria outro
POST http://localhost:8080/usuarios
Content-Type: application/json

{
  "nome": "Bob Souza",
  "email": "bob@email.com",
  "senhaLimpa": "30dfsf9d",
  "taxId": "987.654.321-11",
  "carteiraWeb3": "0x8888bB67C8901234567890abcdef1234567890bb",
  "countryCode": "US"
}

### colocar user 1 no grupo 1

POST http://localhost:8080/cotas/comprar
Content-Type: application/json

{
  "usuarioId": 2,
  "grupoId": 1
}

### sorteia
POST http://localhost:8080/assembleia/grupos/1/sortear
Content-Type: application/json



###cria outro
POST http://localhost:8080/grupos/iniciar/1
Content-Type: application/json


### busca 1 usuario
GET http://localhost:8080/usuarios/2
Content-Type: application/json

### lista todos os usuarios
GET http://localhost:8080/usuarios
Content-Type: application/json

### busca 1 usuario
PATCH http://localhost:8080/usuarios/1
Content-Type: application/json

{
  "nome": "Gabriel Arcanjo Santos de Camargo"
}

### Buscar todos os grupos
GET http://localhost:8080/grupos?status=EM_ANDAMENTO
Content-Type: application/json


### Buscar um grupos
GET http://localhost:8080/grupos/1
Content-Type: application/json

### Buscar cotas por grupo
GET http://localhost:8080/grupos/1/cotas
Content-Type: application/json


