### Criar um Novo Grupo de Consórcio
POST http://localhost:8080/grupos/criar
Content-Type: application/json

{
  "nome": "Consorcio biz2025",
  "valorCota": 200.00,
  "vagasMaximas": 100,
  "duracaoMeses": 50,
  "enderecoContrato": "0x4738f10fD066aF1C3DeBD606e6CDc9a6dCA7D892",
  "aceitaLances": true,
  "tipoLanceAdicional": "LIVRE"
}
### Criar um novo usuário
POST http://localhost:8080/usuarios
Content-Type: application/json

{
"nome": "Andre Barbosa",
"email": "andrezin@email.com",
  "senhaLimpa": "132fddfsdf9fh",
"taxId": "843.456.789-10",
"carteiraWeb3": "0x90F8bf6A479f320ead074411a4B0e7944EAE8629",
  "countryCode": "BR"
}

###cria outro
POST http://localhost:8080/usuarios
Content-Type: application/json

{
  "nome": "Bob Souza",
  "email": "bob@email.com",
  "senhaLimpa": "30dfsf9d",
  "taxId": "987.654.321-11",
  "carteiraWeb3": "0x8888bB67C8901234567890abcdef1234567890bb",
  "countryCode": "US"
}

### colocar user 1 no grupo 1

POST http://localhost:8080/cotas/comprar
Content-Type: application/json

{
  "usuarioId": 3,
  "grupoId": 3
}

### sorteia
POST http://localhost:8080/assembleia/grupos/3/sortear
Content-Type: application/json



### inicia o grupo
PATCH http://localhost:8080/grupos/iniciar/3
Content-Type: application/json


### busca 1 usuario
GET http://localhost:8080/usuarios/3
Content-Type: application/json

### lista todos os usuarios
GET http://localhost:8080/usuarios
Content-Type: application/json

### busca 1 usuario
PATCH http://localhost:8080/usuarios/1
Content-Type: application/json

{
  "nome": "Gabriel Arcanjo Santos de Camargo"
}

### Buscar todos os grupos
GET http://localhost:8080/grupos
Content-Type: application/json


### Buscar um grupos
GET http://localhost:8080/grupos/3
Content-Type: application/json

### Buscar cotas por grupo
GET http://localhost:8080/grupos/3/cotas
Content-Type: application/json

### Buscar fatura por cota
GET http://localhost:8080/pagamentos/cota/4
Content-Type: application/json
